//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Actor
    {
        public Actor()
        {
            this.Movie = new HashSet<Movie>();
        }
    
        public string name { get; set; }
        public System.DateTime birthdate { get; set; }
        public string biography { get; set; }
    
        public virtual ICollection<Movie> Movie { get; set; }
    }
}
