//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Movie
    {
        public Movie()
        {
            this.Actor = new HashSet<Actor>();
            this.Director = new HashSet<Director>();
            this.Genre = new HashSet<Genre>();
        }
    
        public string title { get; set; }
        public int year { get; set; }
        public string description { get; set; }
        public Nullable<int> rank { get; set; }
    
        public virtual ICollection<Actor> Actor { get; set; }
        public virtual ICollection<Director> Director { get; set; }
        public virtual ICollection<Genre> Genre { get; set; }
    }
}
